---
- name: "Create install dir"
  ansible.builtin.file:
    group: root
    mode: "0755"
    name: "{{ granulate_install_dir }}"
    owner: root
    state: directory
  become: true
  tags: ["ct-granulate"]

- name: "Download application (IECM)"
  ansible.builtin.get_url:
    dest: "{{ granulate_install_dir }}/{{ granulate_binary_name }}"
    group: root
    mode: "0744"
    owner: root
    url: "{{ granulate_download_url }}/gprofiler_{{ ct_arch }}"
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  tags: ["ct-granulate"]

- name: "Render launch script (NL)"
  ansible.builtin.template:
    dest: "/usr/local/bin/run_granulate.sh"
    group: root
    mode: "0700"
    owner: root
    src: "run_granulate.sh.j2"
  no_log: true
  become: true
  tags: ["ct-granulate"]
...
